config/routes.rb
Rails.application.routes.draw do
  get 'teamrelationships/create'
  get 'teamrelationships/destroy'

  get 'technologies/index'
  
  resources :teams do
    member do
      get 'join'
      get 'leave'
    end
  end
  
  get 'relationships/create'
  get 'relationships/destroy'

  resources :teamrelationships, only: [:create, :destroy]

  resources :projects
  get 'welcome/index'
  
  resources :technologies
  get 'technologies/index'
  
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  root 'welcome#index'

  get 'aboutus' => 'static#about-us', as: :about
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :username
  attr_accessor :login
  
  def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end
  
  validates :username, presence: true, length: {maximum: 255}, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]*\z/, message: "may only contain letters and numbers." }
  
   
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :projects
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end
  
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  
  has_many :teamrelationships, dependent: :destroy
  has_many :teams, through: :teamrelationships

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "default-avatar.png"

  def join?(team)
    teamrelationships.find_by_team_id(team.id)
  end

  def join!(team)
    teamrelationships.create!(team_id: team.id)
  end  

  def leave!(team)
    teamrelationships.find_by_team_id(team.id).destroy
  end

  def self.search(query)
      where("username like ?","#{query}%")
  end 

  has_many :notifications
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Notification.where("user_id IN (#{following_ids}) ", 
                      user_id: id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /user
  # GET /users.json
  def index
    if params[:search]
      @users = User.search(params[:search])
    else  
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  
  def show
        @user = User.find(params[:id])
        @projects = Project.where("user_id==?", @user.id )
        @teams_rel = Teamrelationship.where("user_id==?", @user.id )
        @following = @user.followed_users
        @followers = @user.followers
        @feed_not = current_user.feed
  end


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users
    render 'following'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers
    render 'followers'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% @user ||= current_user %>
  <%= render "following"%>
  <%= render "followers"%>
  <a type="button" data-toggle="modal" data-target="#following" class ="title-link">
  <strong id="following">
      <%= @user.followed_users.count %>
    </strong>
    following  
  </a>

  <a type="button" data-toggle="modal" data-target="#followers " class ="title-link">
  <strong id="followers" >
      <%= @user.followers.count %>
    </strong>
    followers
  </a>

app/views/users/_follow1.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-default" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user !=@user %>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow1' %>
  <% end %>
<% end %> 

app/views/users/_followers.html.erb
 <div class="modal fade" id="followers" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Followers</h4>
      </div>
      <div class="modal-body">
        <% @followers.each do |user| %>
        <div class="row">
        <div class="col-xs-4"> <%= image_tag user.avatar, :class =>"img-responsive"%>
        </div>
        <div class="col-xs-4"><%= link_to user.username, user, :class =>"title-link text-left"%>
        </div>
      	</div>
    	<% end %>
      </div> 
    </div>
  </div>
</div>


    

app/views/users/_following.html.erb
 <div class="modal fade" id="following" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Following</h4>
      </div>
      <div class="modal-body">
        <% @following.each do |user| %>
        <div class="row">
        <div class="col-xs-4"> <%= image_tag user.avatar, :class =>"img-responsive" %>
        </div>
        <div class="col-xs-8"><%= link_to user.username, user, :class =>"title-link text-left"%> </div>
      </div>
    	<% end %>
      </div> 
    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/followers.html.erb
 <h1>Followers</h1>

    <% @users.each do |user| %>
      <%= link_to user.username, user %>
    <% end %>

app/views/users/following.html.erb
 <h1>Following</h1>

    <% @users.each do |user| %>
      <%= link_to user.username, user %>
    <% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>
<%=form_tag(users_path, :method => "get") do%>          
    <%= text_field_tag :search, params[:search], placeholder: "Search Teams", :class => 'navbar-link'%>           
<%end%>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User',new_user_path %>

app/views/users/show.html.erb
<div class="container">
    <div class="row profile">
        <div class="col-md-3">
            <div class="profile-sidebar">
                <!-- SIDEBAR USERPIC -->
                <div class="profile-userpic">
                    <%= image_tag(current_user.avatar.url(:thumb), :alt => "default-avatar", :class =>"img-responsive")%>
                </div>
                
                <div class="profile-usertitle">
                    <div class="profile-usertitle-name">
                        <%= @user.username %>
                    </div>
                </div>
                <!-- END SIDEBAR USER TITLE -->
                <!-- SIDEBAR BUTTONS -->
                <div class="profile-userbuttons">
                    <%= render 'follow' %>
                    <%= render 'follow_form' if signed_in?%>
   
                    
                </div>
                <!-- END SIDEBAR BUTTONS -->
                <!-- SIDEBAR MENU -->
                <div class="profile-usermenu">
                    <ul class="nav">
                        <li class="active">
                            <a href="#">
                            <i class="glyphicon glyphicon-home"></i>
                            Overview </a>
                        </li>
                        <% if current_user ==@user %>
                        <li>
                            <%= link_to edit_user_registration_path do %>
                                <%= content_tag :i , "" ,:class=>"glyphicon glyphicon-user" %>
                                <%=  "Account Settings"  %>
                            <% end %>
                            
                             </a>
                        <% end %>
                        </li>
                    </ul>
                </div>
                <!-- END MENU -->
            </div>
        </div>
        <div class="col-md-9">
            <div class="profile-content">
              <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel">
                    <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title">
                        <div class="row">
                        <div class="col-xs-8 title ">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                          Projects
                        </a>
                      </div>
                      <% if current_user ==@user %>
                      <div class="col-xs-4 text-right">
                          <%= link_to 'Add', new_project_path, :class => "btn banner-btn " %>

                      </div>
                      <% end %>
                    </div>
                      </h4>
                    </div>
                    
                    <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
                      <div class="panel-body">
                        
                        <% @projects.each do |project| %>
                        <div class="row">
                        <div class="col-xs-12">
                          <div class=" col-xs-4">
                          <%= image_tag project.avatar_project, :class =>"img-responsive"%>
                          </div>
                          <div class=" col-xs-4">
                            <h4><%= link_to project.name, project, :class =>"title-link" %></h4>
                            <p><%= project.description %></p>
                          </div>
                            <% if current_user ==@user %>
                            <div class=" col-xs-4 text-right">
                              <%= link_to 'Edit', edit_project_path(project), :class => "btn banner-btn " %>
                                <%= link_to 'Delete', project, :class => "btn banner-btn-leave ", method: :delete, data: { confirm: 'Are you sure?' } %>
                            </div>
                            <%end %>
                          </div>
                        </div>
                          <% end %>

                      </div>
                    </div>
                    
                  </div>
                  
                  <div class="panel">
                    <div class="panel-heading" role="tab" id="headingTwo">
                      <h4 class="panel-title">
                        <div class="row ">
                        <div class="col-xs-8 title">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                          Teams
                        </a>
                      </div>
                      <% if current_user ==@user %>
                      <div class="col-xs-4 text-right">
                          <%= link_to 'Add', new_team_path, :class => "btn banner-btn" %>
                      </div>
                      <% end %>
                    </div>
                      </h4>
                    </div>
                    
                    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                      <div class="panel-body">
                          <% @teams_rel.each do |team_rel| %>
                            <div class="col-xs-12">
                              <h4><%= link_to team_rel.team.name, team_rel.team , :class =>"title-link"%></h4>
                            </div>
                          <% end %>                         

                        </div>
                    </div>
                  </div>
                <% if current_user ==@user %>
                <div class="panel">
                    <div class="panel-heading" role="tab" id="headingThree">
                      <h4 class="panel-title">
                        <div class="row ">
                        <div class="col-xs-8 title">
                        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
                          Notifications
                        </a>
                      </div>
                    </div>
                      </h4>
                    </div>
                    
                    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
                      <div class="panel-body">
                          <% @feed_not.each do |feed| %>
                            <div class="col-xs-12">
                              <h4><%=link_to feed.name, feed.link%></h4>
                            </div>
                          <% end %>                         

                        </div>
                    </div>
                  </div>
              <%end%>
    </div>
</div>