config/routes.rb
Rails.application.routes.draw do
  get 'teamrelationships/create'
  get 'teamrelationships/destroy'

  get 'technologies/index'
  
  resources :teams do
    member do
      get 'join'
      get 'leave'
    end
  end
  
  get 'relationships/create'
  get 'relationships/destroy'

  resources :teamrelationships, only: [:create, :destroy]

  resources :projects
  get 'welcome/index'
  
  resources :technologies
  get 'technologies/index'
  
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :relationships, only: [:create, :destroy]

  root 'welcome#index'

  get 'aboutus' => 'static#about-us', as: :about
end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :user
    validates :user_id, presence: true
    validates :name, presence: true
    belongs_to :team
    validates :team_id, presence: true
    
    has_attached_file :avatar_project, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "project-default.jpg"
    validates_attachment_content_type :avatar_project, content_type: /\Aimage\/.*\Z/
    
    def self.search(query)
    	where("name like ?","#{query}%")
    end	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /projects
  # GET /projects.json
  def index
    if params[:search]
      @projects = Project.search(params[:search])
    else
      @projects = Project.all
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    Notification.create(user_id: current_user.id, tipo: 1, name: current_user.username + " has created a new project " + @project.name, link: current_user.id)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :avatar, :github_url, :avatar_project, :team_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, url: projects_path, html: { multipart: true }) do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <section class="login-form">
  
      <div class="row">
                
        <div class="col-xs-12">
          <div class="inner-addon left-addon">
              <i class="glyphicon glyphicon-list-alt"></i>
               <%= f.text_field :name, autofocus: true , :class => "form-control input-lg", :placeholder =>"Project Name"%>
          </div>
          
        </div>
        
        <div class="col-xs-12">
          <div class="inner-addon left-addon">
              <i class="glyphicon glyphicon-pencil"></i>
               <%= f.text_area :description, autofocus: true , class: "form-control input-lg", :placeholder =>"Short description of you project ..." %>
          </div>
          
        </div>

        <div class="col-xs-12">
          <div class="inner-addon left-addon">
              <i class="glyphicon glyphicon-eye-open"></i>
               <%= f.url_field :github_url, autofocus: true , :class => "form-control input-lg", :placeholder =>"Github Url"%>
          </div>
        </div>
        
        <div class="field">
        <%= f.select :team_id, Team.all.where("user_id==?", current_user.id).collect { |p| [ p.name, p.id ] } %>

    </div>
        
     <div class="col-xs-12 text-right">
      <%= f.submit "Create",  :class => "btn btn-lg btn-success"%>
      <%= link_to 'Back', current_user, :class => "btn btn-lg btn-default" %>
     </div>

    <% end %>

app/views/projects/edit.html.erb
	<div class="row log-in">
  
<div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

    <h2 class="text-center">Edit Project</h2>
  		<%= render 'form' %>
			</div>
		</form>
		</section>
    </div>
</div>
</div>

app/views/projects/index.html.erb
 <div class="bg">
    <div class="banner-info">
      <div class="container">
          <h1><span>Our</span><br/><label>Projects</label></h1>
      </div>
    </div>
  </div>

<div class="container container-search">
  <%=form_tag(projects_path, :method => "get") do%>          
   <%= text_field_tag :search, params[:search], :class => 'input-lg', :placeholder =>" Enter a project name"%>        
          <%end%>
          </div>
          
    <div class="container-fluid container-compressed">  
      <div class="about">
        <div class="head-section">

        </div>
          
          <div class="container">
            <h3><span>Recent</span><label>Projects .</label></h3>
          </div>
        </div>
        
          <div class="about-grids">
            
            <% @projects.each do |project| %>
            <div class="col-md-4 about-grid">
              <div class="about-grid-info">
                <h4 class="text-center"><%= link_to project.name, project%></h4>
              </div>
                <div class="col-md-12 text-center">
                <p><%= project.description %></p>
              </div>
              <div class=" col-md-12 text-center">
              <%= image_tag project.avatar_project, :class =>"about-grid-pic" %>
              </div>
              </div>
              <% end %>
            </div>
             
            </div>
          </div>            
        </div>
      </div>
</div>

app/views/projects/new.html.erb
<div class="row log-in">
  
<div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">

    <h2 class="text-center">New Project</h2>
  		<%= render 'form' %>
    
			</div>
			
		</form>
		</section>

    </div>
</div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid container-compressed">
<div class="panel panel-default panel-show">
  <div class="panel-body">
    <div class="col-xs-7">
		<%= image_tag @project.avatar_project ,:class => "img-responsive img-rounded"%>
</div>
<div class="col-xs-5">
	<h1>
	  <%= @project.name %>
	</h1>
	<h2 class="text-left">Created by: <em> <%= link_to @project.user.username, @project.user , :class =>"title-link"%></em></h2>
	<blockquote>
  		<p><%= @project.description %></p>

	</blockquote>
	
	
	<p class="text-right"> 
		<%= link_to @project.github_url do %>
           <%= image_tag "git-logo.png" ,:class => "img-link"%>
        <% end %>
	</p>
</div>
</div>
  </div>
</div>